# Generated by Django 4.0.6 on 2022-07-16 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlessons',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_lesson', to=settings.AUTH_USER_MODEL),
        ),
    ]
