# Generated by Django 4.0.6 on 2022-07-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('students_lessons', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlessons',
            name='course',
        ),
        migrations.AlterField(
            model_name='studentlessons',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.student'),
        ),
    ]
