# Generated by Django 4.0.6 on 2022-07-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('students_lessons', '0003_remove_studentlessons_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlessons',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_lessons', to='lessons.lesson'),
        ),
    ]
