# Generated by Django 4.0.6 on 2022-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='categories.category'),
        ),
    ]
