version: "3.7"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 45433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: psql -U $POSTGRES_USER $POSTGRES_DB || exit 1
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5m

volumes:
  pgdata:
