# Generated by Django 4.0.6 on 2022-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0002_rename_owner_id_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='categories.category'),
        ),
    ]
