# Generated by Django 4.0.6 on 2022-07-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='categories',
        ),
    ]
